model:
  _target_: speedit.networks.dit.DiT_XL_2

experiment_dir: outputs/dit_xl2

diffusion:
  _target_: speedit.diffusion.iddpm.IDDPM
  timestep_respacing: ""

data:
  dataset:
    _target_: speedit.dataset.image.image_dataest
    root: /home/kwang/datasets/imagenet/train
    image_size: ${image_size}

  batch_size: 8
  num_workers: 4
