model:
  _target_: speedit.networks.dit.DiT_S_2
  num_classes: ${num_classes}

experiment_dir: outputs/dit_s2_faster

diffusion:
  _target_: speedit.diffusion.iddpm.IDDPM
  timestep_respacing: ""
  faster: true

data:
  _target_:
  dataset:
    _target_: speedit.dataset.image.image_dataest
    root: /data1/xinpeng/imagenet/train
    image_size: ${image_size}

  batch_size: 32
  num_workers: 4

inference:
  diffusion:
    timestep_respacing: '250'
  guidance_scale: 1
  per_proc_batch_size: 32
  num_samples: 10_000


max_iters: 1000000
