diffusion:
  _target_: speedit.diffusion.speed.Speed_IDDPM
  timestep_respacing: ""


data:
  dataset:
    root: /mnt/public/yuanzhihang/ffhq/images256x256/



experiment_dir: /mnt/public/yuanzhihang/outputs/ffhq/faster
