experiment_dir: /mnt/public/yuanzhihang/outputs/ffhq/base

diffusion:
  _target_: speedit.diffusion.iddpm.IDDPM
  timestep_respacing: ""


data:
  dataset:
    root: /mnt/public/yuanzhihang/ffhq/images256x256/
