experiment_dir: outputs/ffhq/quad_base

diffusion:
  _target_: speedit.diffusion.iddpm.IDDPM
  timestep_respacing: ""
  noise_schedule: quad


data:
  dataset:
    root: /mnt/public/yuanzhihang/ffhq/images256x256/
