diffusion:
  _target_: speedit.diffusion.speed.Speed_IDDPM
  timestep_respacing: ""
  noise_schedule: quad



data:
  dataset:
    root: /mnt/public/yuanzhihang/ffhq/images256x256/



experiment_dir: outputs/ffhq/quad_faster
