diffusion:
  _target_: speedit.diffusion.speed.Speed_IDDPM
  timestep_respacing: ""


data:
  dataset:
    root: /home/yuanzhihang/metfaces/images

experiment_dir: /mnt/public/yuanzhihang/outputs/metfaces/faster
