experiment_dir: /mnt/public/yuanzhihang/outputs/metfaces/base

diffusion:
  _target_: speedit.diffusion.iddpm.IDDPM
  timestep_respacing: ""


data:
  dataset:
    root: /home/yuanzhihang/metfaces/images
