diffusion:
  _target_: speedit.diffusion.speed.Speed_IDDPM
  timestep_respacing: ""
  weighting: theory

vae:
  _target_: diffusers.models.AutoencoderKL.from_pretrained
  pretrained_model_name_or_path: transformers/sd-vae-ft-ema

data:
  dataset:
    root: /mnt/public/yuanzhihang/metfaces

experiment_dir: /mnt/public/yuanzhihang/outputs/metfaces/theory
