seed: 0

# path configuration
experiment_dir: outputs/faster_256_imagenet_xl_2
experiment_name: base

ckpt_path:
resume_training:

# logging configuration
ckpt_every: 10000
log_every: 100

# tensorboard loss loggign
enable_tensorboard_log: true

# you must run wandb log before enable_wandb_log
enable_wandb_log: false
wandb_api_key: d72b5534e4e1c99522d1b8b106cb7b65ea764e59
wandb:
  _target_: wandb.init
  project: diffusion-acceleration
  name: debug
  # you can add other argument likes group, entity in config
  # entity
  # group

# save checkpoint first
save_firt_step_ckpt: false


# resume training path
allow_tf32: true
